import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, FileDown, FilePenLine, Info, RotateCcw } from 'lucide-react'

const TYPES=[
  ['application','Blank application form','Collect applicant, income and reference information.'],
  ['lease','Lease agreement draft','Create a property-specific residential lease draft.'],
  ['renewal','Renewal addendum','Record an agreed extension and changed terms.'],
  ['demand','Letter of demand','Demand payment of an identified overdue amount.'],
  ['breach','Breach notice','Notify the tenant of a specified alleged breach and opportunity to remedy.']
]
const money=n=>Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})
const address=p=>[p?.address,p?.suburb,p?.province].filter(Boolean).join(', ')

function defaultDraft(type,p){const lease=p?.activeLease||{};const common={landlord:'',tenant:lease.tenant_name||'',property:address(p),date:'',rent:lease.monthly_rent||p?.monthly_rent||'',deposit:lease.deposit_amount||p?.deposit_amount||'',start:lease.start_date||'',end:lease.end_date||'',extras:'',notes:''}
  if(type==='application')return {...common,occupation:'',documents:'Copy of identification; proof of income; recent bank statements; proof of current address'}
  if(type==='lease')return {...common,paymentDay:'1',escalation:'',occupants:'',pets:'',utilities:'',special:'',noticeAddressLandlord:'',noticeAddressTenant:'',landlordJuristic:'unsure',tenantType:'natural',ordinaryCourse:'unsure',tenantOverThreshold:'unsure',fixedTerm:'yes',exemption:'no'}
  if(type==='renewal')return {...common,newStart:lease.end_date||'',newEnd:'',newRent:lease.monthly_rent||'',newDeposit:'',changes:'All other terms remain unchanged unless recorded in this addendum.'}
  if(type==='demand')return {...common,amount:'',dueDate:'',description:'Outstanding rental and/or charges',paymentDeadline:'',paymentDetails:''}
  return {...common,breachDetails:'',leaseClause:'',remedyRequired:'',remedyDeadline:'',deliveryMethod:''}
}

export function DocumentsModule({properties,notify}){
  const [type,setType]=useState('application');const [propertyId,setPropertyId]=useState(properties[0]?.id||'');const property=properties.find(p=>p.id===propertyId)
  const key=`myrental_document_${type}_${propertyId}`
  const load=()=>{try{return {...defaultDraft(type,property),...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return defaultDraft(type,property)}}
  const [draft,setDraft]=useState(load)
  useEffect(()=>setDraft(load()),[type,propertyId])
  useEffect(()=>{if(propertyId)localStorage.setItem(key,JSON.stringify(draft))},[draft,key,propertyId])
  const set=(name,value)=>setDraft(v=>({...v,[name]:value}))
  const reset=()=>{const fresh=defaultDraft(type,property);setDraft(fresh);localStorage.removeItem(key);notify('Draft reset')}
  if(!properties.length)return <section><div className="page-intro"><div><span className="eyebrow">DOCUMENTS</span><h2>Add a property first</h2><p>Documents are customised to the selected property.</p></div></div></section>
  return <section className="documents-page"><div className="page-intro no-print"><div><span className="eyebrow">LANDLORD DOCUMENT CENTRE</span><h2>Documents and notices</h2><p>Create an editable starting draft, then have legally important documents reviewed before use.</p></div></div>
    <div className="document-types no-print">{TYPES.map(([id,title,text])=><button className={type===id?'active':''} key={id} onClick={()=>setType(id)}><FilePenLine/><span><b>{title}</b><small>{text}</small></span></button>)}</div>
    <article className={`document-risk no-print ${['demand','breach','lease'].includes(type)?'high':''}`}><AlertTriangle/><div><b>{['demand','breach'].includes(type)?'Check before sending':'Template—not legal advice'}</b><p>{['demand','breach'].includes(type)?'Do not assume a standard remedy period or delivery method applies. Check the signed lease, the CPA position, the nature of the breach and current law with a qualified South African property attorney. Never use self-help measures such as changing locks or cutting services.':'This document is an administrative starting point. It is not a substitute for an attorney-drafted agreement suited to the property and parties.'}</p></div></article>
    <div className="document-workspace"><aside className="document-fields no-print"><label>Property<select value={propertyId} onChange={e=>setPropertyId(e.target.value)}>{properties.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><DocFields type={type} draft={draft} set={set}/><div className="document-actions"><button onClick={reset}><RotateCcw/>Reset</button><button className="primary" onClick={()=>window.print()}><FileDown/>Save / print PDF</button></div><small className="autosave">Draft saved automatically on this device.</small></aside><DocumentPreview type={type} draft={draft} property={property}/></div>
  </section>
}

function Input({label,name,value,set,type='text',rows}){return <label>{label}{rows?<textarea rows={rows} value={value||''} onChange={e=>set(name,e.target.value)}/>:<input type={type} value={value||''} onChange={e=>set(name,e.target.value)}/>}</label>}
function DocFields({type,draft,set}){const common=<><Input label="Landlord full name" name="landlord" value={draft.landlord} set={set}/><Input label="Tenant / applicant name" name="tenant" value={draft.tenant} set={set}/><Input label="Document date" name="date" value={draft.date} set={set} type="date"/></>;
  if(type==='application')return <>{common}<Input label="Proposed occupation date" name="occupation" value={draft.occupation} set={set} type="date"/><Input label="Monthly rent (R)" name="rent" value={draft.rent} set={set} type="number"/><Input label="Deposit (R)" name="deposit" value={draft.deposit} set={set} type="number"/><Input label="Tenant-paid extras" name="extras" value={draft.extras} set={set}/><Input label="Documents requested" name="documents" value={draft.documents} set={set} rows={3}/></>
  if(type==='lease')return <><CpaAssessment draft={draft} set={set}/>{common}<Input label="Start date" name="start" value={draft.start} set={set} type="date"/><Input label="End date" name="end" value={draft.end} set={set} type="date"/><Input label="Monthly rent (R)" name="rent" value={draft.rent} set={set} type="number"/><Input label="Payment day" name="paymentDay" value={draft.paymentDay} set={set} type="number"/><Input label="Deposit (R)" name="deposit" value={draft.deposit} set={set} type="number"/><Input label="Escalation" name="escalation" value={draft.escalation} set={set}/><Input label="Approved occupants" name="occupants" value={draft.occupants} set={set}/><Input label="Pets" name="pets" value={draft.pets} set={set}/><Input label="Utilities and monthly charges" name="utilities" value={draft.utilities} set={set} rows={3}/><Input label="Special conditions" name="special" value={draft.special} set={set} rows={4}/></>
  if(type==='renewal')return <>{common}<Input label="New start date" name="newStart" value={draft.newStart} set={set} type="date"/><Input label="New end date" name="newEnd" value={draft.newEnd} set={set} type="date"/><Input label="New monthly rent (R)" name="newRent" value={draft.newRent} set={set} type="number"/><Input label="Additional deposit (if agreed)" name="newDeposit" value={draft.newDeposit} set={set} type="number"/><Input label="Changed terms" name="changes" value={draft.changes} set={set} rows={5}/></>
  if(type==='demand')return <>{common}<Input label="Amount due (R)" name="amount" value={draft.amount} set={set} type="number"/><Input label="Original due date" name="dueDate" value={draft.dueDate} set={set} type="date"/><Input label="What amount relates to" name="description" value={draft.description} set={set} rows={3}/><Input label="Deadline stated in letter" name="paymentDeadline" value={draft.paymentDeadline} set={set} type="date"/><Input label="Payment instructions" name="paymentDetails" value={draft.paymentDetails} set={set} rows={3}/></>
  return <>{common}<Input label="Lease clause relied upon" name="leaseClause" value={draft.leaseClause} set={set}/><Input label="Exact facts of alleged breach" name="breachDetails" value={draft.breachDetails} set={set} rows={4}/><Input label="Action required to remedy" name="remedyRequired" value={draft.remedyRequired} set={set} rows={3}/><Input label="Remedy deadline—verify first" name="remedyDeadline" value={draft.remedyDeadline} set={set} type="date"/><Input label="Planned delivery method" name="deliveryMethod" value={draft.deliveryMethod} set={set}/></>}

function Choice({title,name,value,set,options}){return <fieldset className="cpa-question"><legend>{title}</legend>{options.map(([id,label])=><label key={id}><input type="radio" name={name} checked={value===id} onChange={()=>set(name,id)}/><span>{label}</span></label>)}</fieldset>}
function cpaResult(d){
  if(d.exemption==='yes')return {level:'review',title:'Attorney review required',text:'A claimed exemption must be verified before using a non-CPA lease.'}
  if(d.ordinaryCourse==='no')return {level:'unlikely',title:'CPA may be less likely to apply',text:'The letting may fall outside the landlord’s ordinary course of business, but this is fact-specific. Use a professionally reviewed non-CPA form only after advice.'}
  if(d.tenantType==='juristic'&&d.tenantOverThreshold==='yes')return {level:'unlikely',title:'CPA generally appears not to apply',text:'A juristic tenant at or above the current statutory threshold is generally excluded. Verify turnover/assets, the current threshold and exceptions.'}
  if(d.landlordJuristic==='yes'&&d.tenantType==='juristic')return {level:'mixed',title:'Section 14 does not apply between juristic persons',text:'Other CPA provisions may still need analysis if the tenant is below the threshold. Do not label the entire lease non-CPA without review.'}
  if(d.ordinaryCourse==='yes'&&d.tenantType==='natural')return {level:'likely',title:'CPA-style lease recommended',text:'The indicators point toward CPA application. Use CPA-compliant fixed-term, expiry, cancellation, plain-language and notice provisions, subject to attorney review.'}
  if(d.ordinaryCourse==='yes'&&d.tenantType==='juristic'&&d.tenantOverThreshold==='no')return {level:'mixed',title:'CPA may apply, but section 14 needs care',text:'A below-threshold juristic tenant may receive CPA protection, while section 14 does not apply if both parties are juristic persons. Attorney review is recommended.'}
  return {level:'review',title:'Result uncertain—do not choose yet',text:'One or more key facts are unknown. Ask an attorney to confirm CPA application before selecting the lease wording.'}
}
function CpaAssessment({draft,set}){const result=cpaResult(draft);return <section className="cpa-assessment"><span className="eyebrow">CPA OR NON-CPA?</span><h3>Answer before drafting</h3><p className="cpa-intro">These questions provide a cautious recommendation only; they do not make a legal determination.</p><Choice title="Does the landlord let property in the ordinary course of a business or repeated rental activity?" name="ordinaryCourse" value={draft.ordinaryCourse} set={set} options={[["yes","Yes"],["no","No—isolated/private letting"],["unsure","Unsure"]]}/><Choice title="What type of tenant will sign the lease?" name="tenantType" value={draft.tenantType} set={set} options={[["natural","Natural person"],["juristic","Company, CC, trust or other juristic person"]]}/>{draft.tenantType==='juristic'&&<Choice title="At signature, does the juristic tenant meet or exceed the current CPA turnover or asset threshold?" name="tenantOverThreshold" value={draft.tenantOverThreshold} set={set} options={[["yes","Yes"],["no","No"],["unsure","Unknown—verify"]]}/>}<Choice title="Is the landlord a company, CC, trust or other juristic person?" name="landlordJuristic" value={draft.landlordJuristic} set={set} options={[["yes","Yes"],["no","No—natural person"],["unsure","Unsure"]]}/><Choice title="Is this a fixed-term lease?" name="fixedTerm" value={draft.fixedTerm} set={set} options={[["yes","Yes"],["no","No"],["unsure","Unsure"]]}/><Choice title="Has an attorney confirmed a specific CPA exemption for this transaction?" name="exemption" value={draft.exemption} set={set} options={[["no","No"],["yes","Yes—retain written advice"]]}/><div className={`cpa-result ${result.level}`}><b>{result.title}</b><p>{result.text}</p></div><ul className="cpa-reminders"><li>Do not decide only because the landlord owns one property or calls the letting “private”.</li><li>The juristic-person monetary threshold must be checked against current law when the lease is signed.</li><li>Section 14 has its own exclusion for transactions between juristic persons.</li><li>The Rental Housing Act still applies even where CPA section 14 does not.</li></ul></section>}

function Line({children}){return <p className="doc-line">{children||'________________________________________'}</p>}
function Signatures(){return <div className="doc-signatures"><span>Landlord signature<b/></span><span>Tenant / applicant signature<b/></span><span>Date<b/></span></div>}
function DocumentPreview({type,draft,property}){const title=TYPES.find(x=>x[0]===type)?.[1];return <article className="document-preview"><header><strong>MyRental SA</strong><span>DRAFT · REVIEW BEFORE USE</span></header><h1>{title}</h1><p className="doc-meta"><b>Property:</b> {address(property)}</p>{type==='application'&&<ApplicationDoc d={draft}/>} {type==='lease'&&<LeaseDoc d={draft}/>} {type==='renewal'&&<RenewalDoc d={draft}/>} {type==='demand'&&<DemandDoc d={draft}/>} {type==='breach'&&<BreachDoc d={draft}/>}<footer>Generated as helpful administrative knowledge only. This is not legal advice and no outcome is guaranteed. Obtain advice from a qualified South African property attorney where appropriate.</footer></article>}
function ApplicationDoc({d}){return <><h2>Proposed rental</h2><Line>Occupation: {d.occupation||'To be agreed'} · Rent: R{money(d.rent)} · Deposit: R{money(d.deposit)}</Line><Line>Tenant-paid extras: {d.extras||'To be specified'}</Line><h2>Applicant details</h2>{['Full legal names','ID / passport number','Mobile and email','Current address','Other occupants and pets'].map(x=><Line key={x}><b>{x}:</b></Line>)}<h2>Employment, income and references</h2>{['Employer / business and occupation','Gross and net monthly income','Employer contact','Current landlord / agent and contact','Previous landlord / agent and contact','Monthly debt commitments'].map(x=><Line key={x}><b>{x}:</b></Line>)}<h2>Documents requested</h2><Line>{d.documents}</Line><h2>Declaration and consent</h2><p>I confirm that the information supplied is true and consent to lawful verification for this rental application. Submitting this form does not create a lease or guarantee approval.</p><Signatures/></>}
function LeaseDoc({d}){const result=cpaResult(d);return <><div className="doc-cpa"><b>CPA assessment: {result.title}</b><p>{result.text}</p></div><p>Between <b>{d.landlord||'[landlord]'}</b> and <b>{d.tenant||'[tenant]'}</b>.</p><h2>1. Term and occupation</h2><p>The proposed lease runs from {d.start||'[start date]'} to {d.end||'[end date]'}. Only these approved occupants may reside at the property: {d.occupants||'[record occupants]'}.</p><h2>2. Rent, deposit and charges</h2><p>Monthly rent is R{money(d.rent)}, payable by day {d.paymentDay||'[day]'} as agreed. The deposit is R{money(d.deposit)} and must be dealt with in accordance with applicable law. Escalation: {d.escalation||'[specify]'}. Utilities/charges: {d.utilities||'[specify]'}</p><h2>3. Use, care and access</h2><p>The tenant must use the property lawfully, take reasonable care of it, report maintenance promptly and comply with agreed rules. The landlord must respect the tenant’s privacy and arrange reasonable access.</p><h2>4. Inspections and condition</h2><p>The parties must complete the legally required joint inspections and attach the ingoing condition report. Fair wear and tear must be distinguished from damage.</p><h2>5. Pets and special conditions</h2><p>Pets: {d.pets||'[specify]'}</p><p>{d.special||'[Insert reviewed special conditions]'}</p><h2>6. Breach, cancellation and notices</h2><p>The applicable notice, remedy, cancellation and CPA provisions must be completed or reviewed by a qualified attorney for the parties and circumstances before signature.</p><Signatures/></>}
function RenewalDoc({d}){return <><p>The landlord <b>{d.landlord||'[landlord]'}</b> and tenant <b>{d.tenant||'[tenant]'}</b> agree, subject to signature and legal review, to extend the lease from {d.newStart||'[date]'} to {d.newEnd||'[date]'}.</p><p>The new monthly rent is <b>R{money(d.newRent)}</b>. Additional deposit, if lawfully agreed: <b>R{money(d.newDeposit)}</b>.</p><h2>Changed terms</h2><p>{d.changes||'No changes recorded.'}</p><p>This addendum and the original lease should be read together. If they conflict, obtain legal advice before signature.</p><Signatures/></>}
function DemandDoc({d}){return <><p><b>Date:</b> {d.date||'[date]'}</p><p>To: <b>{d.tenant||'[tenant]'}</b></p><h2>Demand for payment</h2><p>Our records indicate that <b>R{money(d.amount)}</b> relating to {d.description||'[describe amount]'} fell due on {d.dueDate||'[due date]'}.</p><p>You are requested to pay by <b>{d.paymentDeadline||'[deadline—verify before use]'}</b> using: {d.paymentDetails||'[payment instructions]'}. If you dispute the amount, provide written reasons and supporting proof promptly.</p><p>No statement in this draft waives either party’s rights. The landlord must verify the lease, amount, notice requirements and applicable law before sending.</p><p>Signed: {d.landlord||'[landlord]'}</p></>}
function BreachDoc({d}){return <><p><b>Date:</b> {d.date||'[date]'}</p><p>To: <b>{d.tenant||'[tenant]'}</b></p><h2>Notice of alleged breach</h2><p>The landlord alleges a breach of {d.leaseClause||'[identify the signed lease clause]'} on these facts:</p><p>{d.breachDetails||'[state objective facts, dates and evidence—avoid exaggeration]'}</p><p>The tenant is requested to remedy the alleged breach by doing the following: {d.remedyRequired||'[specific lawful action]'}.</p><p>Proposed deadline: <b>{d.remedyDeadline||'[verify the correct period before sending]'}</b>.</p><p>This draft does not itself determine cancellation or eviction rights. Do not threaten or take steps not permitted by the lease and law. Obtain attorney advice before escalation.</p><p>Signed: {d.landlord||'[landlord]'}</p></>}
