import { useEffect, useState } from 'react'
import { supabase } from './supabase'
import { AlertTriangle, Camera, FileDown, ImagePlus, Info, Loader2, Plus, Save, ShieldCheck, Trash2, X } from 'lucide-react'

const COMMON=['Ceiling','Walls','Floor','Windows','Doors','Electrical points and lights','Blinds / curtain rods','Air-conditioners','Remotes and keys']
const AREA_TYPES={
  living:{label:'Living area / passage',items:COMMON},
  kitchen:{label:'Kitchen',items:[...COMMON,'Oven','Stove / hob','Extractor fan','Cupboard tops / worktops','Cupboards inside','Cupboards outside','Sink','Taps','Washing-machine connection']},
  bathroom:{label:'Bathroom',items:[...COMMON,'Shower','Toilet','Bath','Basin','Mirror','Extractor fan','Cupboard / vanity']},
  bedroom:{label:'Bedroom',items:[...COMMON,'Built-in cupboards inside','Built-in cupboards outside']},
  braai:{label:'Braai room / area',items:[...COMMON,'Sink','Taps','Built-in braai','Braai grid and accessories']},
  exterior:{label:'Exterior / garden',items:['Roof','Gutters and downpipes','Garden','Pool and equipment','Gates and motors','Boundary walls / fences','Exterior property walls','Paving / pathways','Outside taps and drains']},
  garage:{label:'Garage / parking',items:[...COMMON,'Garage door','Garage-door motor','Garage remotes','Shelving / cupboards']},
  systems:{label:'General home systems',items:['Alarm system','Alarm keypad / remotes','Irrigation system','Irrigation controller','Electric fence / energiser','Intercom / access system','Electricity meter','Water meter','Main keys and access remotes']}
}
const START_AREAS=[['living','Entrance / passage'],['living','Lounge / living area'],['kitchen','Kitchen'],['bedroom','Main bedroom'],['bedroom','Bedroom 2'],['bathroom','Bathroom'],['braai','Braai room / area'],['exterior','Exterior / garden'],['garage','Garage / parking'],['systems','General home systems']]
const CONDITIONS=['Not checked','Good','Fair','Poor','Damaged','Not applicable']
const GUIDES={
  ingoing:{title:'Ingoing inspection',intro:'Complete jointly with the tenant before occupation. Record every existing defect and give both parties the signed report and referenced photographs.'},
  interim:{title:'Interim inspection',intro:'Arrange reasonable access, respect privacy and compare condition against the ingoing report. Focus on maintenance and developing deterioration.'},
  outgoing:{title:'Outgoing inspection',intro:'Arrange the joint inspection at a mutually convenient time within the three days before lease expiry and compare directly against the ingoing report.'}
}
const makeItem=name=>({id:crypto.randomUUID(),name,condition:'Not checked',notes:''})
const makeArea=(type,name)=>({id:crypto.randomUUID(),type,name:name||AREA_TYPES[type].label,items:AREA_TYPES[type].items.map(makeItem),notes:'',action:'',images:[]})
const blankForm=(property,type)=>({id:crypto.randomUUID(),date:'',tenant:property?.activeLease?.tenant_name||'',type,areas:START_AREAS.map(([t,n])=>makeArea(t,n)),landlordNotes:'',tenantNotes:'',status:'draft'})

export function InspectionModule({properties,ownerId,notify}){
  const [propertyId,setPropertyId]=useState(properties[0]?.id||'');const [type,setType]=useState('ingoing');const property=properties.find(p=>p.id===propertyId)
  const localKey=`myrental_inspection_v2_${propertyId}_${type}`
  const [form,setForm]=useState(()=>blankForm(property,type));const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState('');const [error,setError]=useState('')
  const hydrateImages=async data=>({...data,areas:await Promise.all((data.areas||[]).map(async area=>({...area,images:await Promise.all((area.images||[]).map(async img=>{if(!img.path)return img;const {data:signed}=await supabase.storage.from('inspection-images').createSignedUrl(img.path,3600);return {...img,url:signed?.signedUrl||''}}))})))})
  const load=async()=>{setError('');let local;try{local=JSON.parse(localStorage.getItem(localKey)||'null')}catch{}setForm(local||blankForm(property,type));if(!ownerId)return;const {data,error:e}=await supabase.from('inspection_reports').select('*').eq('owner_id',ownerId).eq('property_id',propertyId).eq('inspection_type',type).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(data)setForm(await hydrateImages(data.report_data));else if(e&&!e.message.includes('does not exist'))setError(e.message)}
  useEffect(()=>{if(propertyId)load()},[propertyId,type,ownerId])
  useEffect(()=>{if(propertyId)localStorage.setItem(localKey,JSON.stringify(form))},[form,localKey,propertyId])
  const update=(key,value)=>setForm(v=>({...v,[key]:value}))
  const updateArea=(id,key,value)=>setForm(v=>({...v,areas:v.areas.map(a=>a.id===id?{...a,[key]:value}:a)}))
  const updateItem=(areaId,itemId,key,value)=>setForm(v=>({...v,areas:v.areas.map(a=>a.id===areaId?{...a,items:a.items.map(i=>i.id===itemId?{...i,[key]:value}:i)}:a)}))
  const changeAreaType=(areaId,nextType)=>setForm(v=>({...v,areas:v.areas.map(a=>a.id===areaId?{...a,type:nextType,items:AREA_TYPES[nextType].items.map(name=>a.items.find(i=>i.name===name)||makeItem(name))}:a)}))
  const addArea=()=>setForm(v=>({...v,areas:[...v.areas,makeArea('living','New room / area')]}));const removeArea=id=>setForm(v=>({...v,areas:v.areas.filter(a=>a.id!==id)}))
  const uploadImages=async(areaId,files)=>{if(!files?.length)return;setUploading(areaId);setError('');const additions=[];for(const file of [...files]){if(!file.type.startsWith('image/'))continue;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${ownerId}/${propertyId}/${form.id}/${areaId}/${crypto.randomUUID()}-${safe}`;const {error:e}=await supabase.storage.from('inspection-images').upload(path,file,{contentType:file.type,upsert:false});if(e){setError(e.message);continue}const {data:signed}=await supabase.storage.from('inspection-images').createSignedUrl(path,3600);additions.push({path,url:signed?.signedUrl||'',name:file.name,caption:''})}setForm(v=>({...v,areas:v.areas.map(a=>a.id===areaId?{...a,images:[...a.images,...additions]}:a)}));setUploading('')}
  const removeImage=async(areaId,path)=>{await supabase.storage.from('inspection-images').remove([path]);setForm(v=>({...v,areas:v.areas.map(a=>a.id===areaId?{...a,images:a.images.filter(i=>i.path!==path)}:a)}))}
  const save=async()=>{setBusy(true);setError('');const clean={...form,areas:form.areas.map(a=>({...a,images:a.images.map(({path,name,caption})=>({path,name,caption}))}))};const payload={id:form.id,owner_id:ownerId,property_id:propertyId,inspection_type:type,inspection_date:form.date||null,tenant_name:form.tenant||null,status:form.status,report_data:clean,updated_at:new Date().toISOString()};const {error:e}=await supabase.from('inspection_reports').upsert(payload);setBusy(false);if(e)setError(e.message);else notify('Inspection notes and images saved')}
  if(!properties.length)return <section><div className="page-intro"><div><span className="eyebrow">INSPECTIONS</span><h2>Add a property first</h2><p>Your inspection will be customised to the property.</p></div></div></section>
  const guide=GUIDES[type]
  return <section className="inspection-page"><div className="page-intro no-print"><div><span className="eyebrow">DETAILED CONDITION REPORT</span><h2>Property inspections</h2><p>Check every component, add notes and securely save photographs from your gallery.</p></div></div><div className="inspection-tabs no-print">{Object.entries(GUIDES).map(([key,g])=><button className={type===key?'active':''} onClick={()=>setType(key)} key={key}>{g.title}</button>)}</div><article className="legal-inspection-note no-print"><ShieldCheck/><div><b>{guide.title}: important</b><p>{guide.intro}</p></div></article>
    <div className="inspection-basics no-print"><label>Property<select value={propertyId} onChange={e=>setPropertyId(e.target.value)}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Inspection date<input type="date" value={form.date} onChange={e=>update('date',e.target.value)}/></label><label>Tenant name<input value={form.tenant} onChange={e=>update('tenant',e.target.value)}/></label></div>
    <div className="inspection-form-head"><div><span className="eyebrow">{type.toUpperCase()} REPORT</span><h2>{property?.name}</h2><p>{[property?.address,property?.suburb,property?.province].filter(Boolean).join(', ')}</p></div><div className="inspection-head-actions no-print"><button onClick={()=>window.print()}><FileDown/>Print / PDF</button><button className="save-inspection" onClick={save} disabled={busy||!!uploading}>{busy?<Loader2 className="spin"/>:<Save/>}Save inspection</button></div></div>{error&&<div className="inspection-error no-print">{error}</div>}
    <div className="area-list">{form.areas.map((area,index)=><article className="inspection-area" key={area.id}><div className="area-title"><span>{index+1}</span><input aria-label="Area name" value={area.name} onChange={e=>updateArea(area.id,'name',e.target.value)}/><select className="no-print" value={area.type} onChange={e=>changeAreaType(area.id,e.target.value)}>{Object.entries(AREA_TYPES).map(([id,t])=><option value={id} key={id}>{t.label}</option>)}</select><button className="no-print" aria-label={`Remove ${area.name}`} onClick={()=>removeArea(area.id)}><Trash2/></button></div><div className="condition-table"><div className="condition-row heading"><b>Item</b><b>Condition</b><b>Notes / exact defect</b></div>{area.items.map(item=><div className="condition-row" key={item.id}><b>{item.name}</b><select value={item.condition} onChange={e=>updateItem(area.id,item.id,'condition',e.target.value)}>{CONDITIONS.map(x=><option key={x}>{x}</option>)}</select><input value={item.notes} onChange={e=>updateItem(area.id,item.id,'notes',e.target.value)} placeholder="Location, mark, crack, missing item or test result…"/></div>)}</div><div className="area-notes"><label>General notes<textarea value={area.notes} onChange={e=>updateArea(area.id,'notes',e.target.value)}/></label><label>Repair / action required<textarea value={area.action} onChange={e=>updateArea(area.id,'action',e.target.value)}/></label></div><div className="area-photos no-print"><div className="photo-upload-head"><div><Camera/><span><b>Area photographs</b><small>Add a room overview plus close-ups of every defect.</small></span></div><label className="gallery-button">{uploading===area.id?<Loader2 className="spin"/>:<ImagePlus/>}{uploading===area.id?'Uploading…':'Choose from gallery'}<input type="file" accept="image/*" multiple onChange={e=>uploadImages(area.id,e.target.files)}/></label></div>{area.images.length>0&&<div className="image-grid">{area.images.map(img=><div className="inspection-image" key={img.path}><img src={img.url} alt={img.caption||img.name}/><button onClick={()=>removeImage(area.id,img.path)} aria-label="Remove image"><X/></button><input value={img.caption||''} onChange={e=>updateArea(area.id,'images',area.images.map(x=>x.path===img.path?{...x,caption:e.target.value}:x))} placeholder="What does this show?"/></div>)}</div>}</div></article>)}</div><button className="add-area no-print" onClick={addArea}><Plus/>Add room or area</button>
    <div className="inspection-signoff"><label>Landlord comments<textarea value={form.landlordNotes} onChange={e=>update('landlordNotes',e.target.value)}/></label><label>Tenant comments / disagreements<textarea value={form.tenantNotes} onChange={e=>update('tenantNotes',e.target.value)}/></label><div className="signature-lines"><span>Landlord name and signature<b/></span><span>Tenant name and signature<b/></span><span>Date<b/></span></div><p>Both parties should receive the complete signed report and referenced photographs.</p></div>
    <section className="photo-guidance no-print"><div className="photo-heading"><Camera/><div><span className="eyebrow">PHOTO METHOD</span><h2>Take useful evidence</h2></div></div><div className="photo-examples">{[['Overview','Photograph every room from opposite corners in good light.'],['Context','Take a wider image showing exactly where a defect is located.'],['Close-up','Take a sharp close-up showing type and approximate size of damage.'],['Proof','Photograph meters, serial numbers, keys, remotes and tested appliances.']].map(([t,p])=><article key={t}><div className="example-frame"><Camera/><span>Example</span></div><h3>{t}</h3><p>{p}</p></article>)}</div></section>
    {type==='ingoing'&&<article className="signature-warning no-print"><AlertTriangle/><div><b>Do not leave the ingoing report unsigned</b><p>An unsigned or incomplete report can cause serious factual disputes and weaken evidence in a deposit dispute before a Rental Housing Tribunal. Record any refusal to sign and obtain legal advice.</p></div></article>}<article className="inspection-disclaimer no-print"><Info/><p><b>Helpful guidance, not legal advice.</b> For disputed damage, deductions, access problems or missed inspection steps, consult a qualified South African property attorney or Rental Housing Tribunal.</p></article>
  </section>
}
