import { useState } from 'react'
import { AlertTriangle, ChevronRight, Scale, ShieldCheck } from 'lucide-react'
import { supabase } from './supabase'

export const LEGAL_VERSION='2026-09-13-v1'

const sections=[
  ['Purpose of the platform','MyRental SA provides organisational tools, general educational information, reminders, checklists and document-preparation assistance for South African private landlords. It is not a law firm, attorney, estate agency, financial adviser, credit bureau or debt-collection service.'],
  ['No legal advice or attorney-client relationship','Information, suggestions, classifications, calculations, templates and generated content are general in nature. They are not a substitute for advice from a qualified South African attorney who has considered the particular lease, parties, facts and current law. Use of the platform does not create an attorney-client relationship.'],
  ['High-risk matters','Users must obtain appropriate professional advice before eviction, lockout, disconnection of services, seizure of possessions, cancellation, serious breach action, disputed deposit deduction, discrimination-sensitive screening, unusual CPA questions or court and tribunal proceedings. The platform must never be used for unlawful self-help.'],
  ['User responsibility','The landlord remains responsible for checking information, selecting appropriate terms, meeting deadlines, complying with applicable laws, keeping evidence, protecting personal information and making every rental-management decision. Automated reminders and guidance may be incomplete, delayed or affected by incorrect user data.'],
  ['Documents and signatures','Drafts, notices, lease terms, addendums and reports must be checked for the specific transaction before use. The user must ensure that the chosen form, delivery method and signature process meet all applicable legal and evidential requirements. Attorney review is strongly recommended.'],
  ['Tenant information and POPIA','The landlord is responsible for having a lawful purpose for collecting tenant and applicant information, providing required notices, limiting access, keeping information accurate and secure, and deleting it when no longer lawfully required. MyRental SA’s separate privacy notice explains platform processing.'],
  ['No guaranteed outcome','MyRental SA does not guarantee tenant suitability, payment, legal compliance, enforceability, successful recovery, dispute outcomes, uninterrupted access or that a reminder will prevent loss. Users should maintain independent copies of critical records and diary important deadlines separately.'],
  ['Fair and lawful limitation','To the maximum extent permitted by applicable law, MyRental SA and its operator will not be liable for indirect, consequential or special loss arising from reliance on platform information or user-entered data. Nothing in these terms excludes rights or liability that cannot lawfully be excluded, including protections under applicable consumer law.'],
  ['Changes and professional review','Legal content may be updated and users may be asked to accept a newer version. This draft must be reviewed and adapted by a South African technology and property-law attorney before commercial launch, including the operator’s legal name, contact details, subscription terms, dispute process and governing-law wording.']
]

export function LegalAcceptance({user,onAccepted}){
  const [checks,setChecks]=useState({terms:false,advice:false,privacy:false});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const ready=Object.values(checks).every(Boolean)
  const accept=async()=>{setBusy(true);setError('');const {error:err}=await supabase.from('legal_acceptances').insert({user_id:user.id,document_version:LEGAL_VERSION,accepted_terms:true,accepted_disclaimer:true,accepted_privacy:true});if(err){setError(err.message);setBusy(false);return}onAccepted()}
  return <div className="legal-shell"><div className="legal-gate"><div className="legal-heading"><span><Scale/></span><div><small>IMPORTANT INFORMATION</small><h1>Before you continue</h1><p>Please understand what MyRental SA can—and cannot—do for you.</p></div></div><div className="legal-summary"><AlertTriangle/><p><b>MyRental SA is not a law firm and does not provide legal advice.</b> It provides general knowledge and administrative tools. Your circumstances may require a qualified South African attorney.</p></div><div className="legal-scroll">{sections.map(([title,text])=><section key={title}><h3>{title}</h3><p>{text}</p></section>)}</div><div className="legal-checks"><label><input type="checkbox" checked={checks.terms} onChange={e=>setChecks({...checks,terms:e.target.checked})}/><span>I have read and accept the Terms of Use and limitations.</span></label><label><input type="checkbox" checked={checks.advice} onChange={e=>setChecks({...checks,advice:e.target.checked})}/><span>I understand this is general information, not legal advice, and I remain responsible for decisions.</span></label><label><input type="checkbox" checked={checks.privacy} onChange={e=>setChecks({...checks,privacy:e.target.checked})}/><span>I accept the Privacy Notice and will handle tenant information lawfully.</span></label></div>{error&&<div className="auth-message">{error}</div>}<button className="legal-accept" disabled={!ready||busy} onClick={accept}>{busy?'Recording acceptance…':'Accept and continue'}<ChevronRight/></button><small className="legal-version">Document version: {LEGAL_VERSION}</small></div></div>
}

export function LegalPage(){return <section><div className="page-intro"><div><span className="eyebrow">LEGAL & PRIVACY</span><h2>Terms and important notices</h2><p>The boundaries that apply whenever MyRental SA is used.</p></div></div><div className="legal-page-warning"><ShieldCheck/><div><b>Helpful knowledge—not legal advice</b><p>Always consult a qualified attorney when a matter could affect legal rights, possession of a home, cancellation, eviction or a disputed sum.</p></div></div><div className="legal-page-sections">{sections.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><p className="legal-version">Current version: {LEGAL_VERSION}</p></section>}
