import { useEffect, useState } from 'react'
import { AlertTriangle, BookOpen, CalendarDays, ChevronRight, ClipboardCheck, FilePenLine, Hammer, Link2, Plus, Receipt, ShieldCheck, UserRound, WalletCards, X } from 'lucide-react'
import { supabase } from './supabase'

const configs={
  Applications:{type:'application',icon:UserRound,eyebrow:'TENANT SCREENING',title:'Tenant applications',description:'Track every application, outstanding information and decision.',add:'Add application',statuses:['Received','Awaiting documents','Under review','Approved','Declined']},
  Inspections:{type:'inspection',icon:ClipboardCheck,eyebrow:'PROPERTY CONDITION',title:'Inspections',description:'Manage ingoing, interim and outgoing inspections.',add:'Schedule inspection',statuses:['Planned','In progress','Awaiting signature','Completed']},
  Documents:{type:'document',icon:FilePenLine,eyebrow:'LEASE DOCUMENTS',title:'Documents and notices',description:'Track leases, addendums, notices and breach records.',add:'Add document record',statuses:['Draft','Awaiting signature','Issued','Completed']},
  Finances:{type:'finance',icon:WalletCards,eyebrow:'RENT & DEPOSITS',title:'Rent and deposits',description:'Record payments, deposits, deductions and refunds.',add:'Add financial record',statuses:['Expected','Received','Overdue','Reconciled','Refunded']},
  Renewals:{type:'renewal',icon:CalendarDays,eyebrow:'LEASE DEADLINES',title:'Renewals and addendums',description:'Manage renewal decisions, new terms and signature progress.',add:'Add renewal',statuses:['Decision needed','Negotiating','Awaiting signature','Completed','Not renewing']}
}

export function RentalModule({name,ownerId,properties,notify}){
  const config=configs[name]||configs.Documents;const Icon=config.icon
  const [items,setItems]=useState([]);const [editing,setEditing]=useState(null);const [loading,setLoading]=useState(true)
  const load=()=>{setLoading(true);supabase.from('rental_records').select('*, properties(name)').eq('owner_id',ownerId).eq('record_type',config.type).order('created_at',{ascending:false}).then(({data})=>{setItems(data||[]);setLoading(false)})}
  useEffect(load,[ownerId,config.type])
  return <section><div className="page-intro"><div><span className="eyebrow">{config.eyebrow}</span><h2>{config.title}</h2><p>{config.description}</p></div><button className="primary" onClick={()=>setEditing({})}><Plus size={18}/>{config.add}</button></div>{loading?<ModuleLoading/>:items.length?<div className="record-list">{items.map(item=><button key={item.id} onClick={()=>setEditing(item)}><span className="record-icon"><Icon/></span><div><small>{item.properties?.name||'No property selected'}</small><b>{item.title}</b><p>{item.notes||'No notes added'}</p></div><span className="record-side"><i>{item.status}</i>{item.due_date&&<small>{formatDate(item.due_date)}</small>}{item.amount!=null&&<strong>R{Number(item.amount).toLocaleString('en-ZA')}</strong>}<ChevronRight/></span></button>)}</div>:<ModuleEmpty icon={Icon} title={`No ${config.title.toLowerCase()} yet`} text={`Select “${config.add}” to create the first record.`}/>} {editing&&<RecordEditor config={config} record={editing} ownerId={ownerId} properties={properties} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);load();notify('Record saved')}}/>}</section>
}

export function MaintenanceModule({ownerId,properties,notify}){
  const [items,setItems]=useState([]);const [editing,setEditing]=useState(null);const [loading,setLoading]=useState(true)
  const load=()=>{setLoading(true);supabase.from('maintenance_items').select('*, properties(name)').eq('owner_id',ownerId).neq('status','Completed').order('created_at',{ascending:false}).then(({data})=>{setItems(data||[]);setLoading(false)})}
  useEffect(load,[ownerId])
  return <section><div className="page-intro"><div><span className="eyebrow">MAINTENANCE</span><h2>Issues and repairs</h2><p>Track responsibility, quotations, costs, follow-ups and completion.</p></div><button className="primary" onClick={()=>setEditing({})}><Plus size={18}/>Log issue</button></div>{loading?<ModuleLoading/>:items.length?<div className="record-list">{items.map(item=><button key={item.id} onClick={()=>setEditing(item)}><span className={`record-icon ${item.urgent?'danger':''}`}><Hammer/></span><div><small>{item.properties?.name}</small><b>{item.issue}</b><p>{item.feedback||'No feedback recorded'}</p></div><span className="record-side"><i>{item.status}</i>{item.last_followed_up&&<small>Followed up {formatDate(item.last_followed_up)}</small>}<ChevronRight/></span></button>)}</div>:<ModuleEmpty icon={Hammer} title="No open maintenance issues" text="Issues logged by the landlord or tenant will appear here."/>}{editing&&<MaintenanceEditor item={editing} ownerId={ownerId} properties={properties} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);load();notify('Maintenance issue saved')}}/>}</section>
}

function RecordEditor({config,record,ownerId,properties,onClose,onSaved}){
  const key=`myrental_${config.type}_draft_${record.id||'new'}`;const blank={property_id:'',title:'',status:config.statuses[0],due_date:'',amount:'',notes:'',record_type:config.type}
  const [form,setForm]=useState(()=>{try{return {...blank,...record,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return {...blank,...record}}});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const set=(k,v)=>setForm({...form,[k]:v});useEffect(()=>localStorage.setItem(key,JSON.stringify(form)),[form,key])
  const save=async e=>{e.preventDefault();setBusy(true);const payload={owner_id:ownerId,property_id:form.property_id||null,record_type:config.type,title:form.title,status:form.status,due_date:form.due_date||null,amount:form.amount?Number(form.amount):null,notes:form.notes||null,updated_at:new Date().toISOString()};const {error:err}=record.id?await supabase.from('rental_records').update(payload).eq('id',record.id):await supabase.from('rental_records').insert(payload);if(err){setError(err.message);setBusy(false);return}localStorage.removeItem(key);onSaved()}
  return <div className="editor-backdrop" onClick={onClose}><form className="lease-editor compact-editor" onSubmit={save} onClick={e=>e.stopPropagation()}><EditorHead eyebrow={config.eyebrow} title={record.id?'Edit record':config.add} onClose={onClose}/><section className="editor-section"><div className="form-grid"><label>Property<select required value={form.property_id||''} onChange={e=>set('property_id',e.target.value)}><option value="">Select property</option>{properties.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>set('status',e.target.value)}>{config.statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="full-field">Title / description<input required value={form.title} onChange={e=>set('title',e.target.value)} placeholder={config.add}/></label><label>Due or action date<input type="date" value={form.due_date||''} onChange={e=>set('due_date',e.target.value)}/></label>{config.type==='finance'&&<label>Amount (R)<input type="number" min="0" step="0.01" value={form.amount||''} onChange={e=>set('amount',e.target.value)}/></label>}<label className="full-field">Notes<textarea rows="5" value={form.notes||''} onChange={e=>set('notes',e.target.value)} placeholder="Add important details, outstanding items or next steps…"/></label></div></section>{error&&<div className="auth-message">{error}</div>}<EditorActions busy={busy} onClose={onClose}/></form></div>
}

function MaintenanceEditor({item,ownerId,properties,onClose,onSaved}){
  const key=`myrental_maintenance_draft_${item.id||'new'}`;const blank={property_id:'',issue:'',reported_by:'Landlord',urgent:false,responsibility:'To assess',status:'Logged',contractor:'',quote_amount:'',actual_cost:'',last_followed_up:'',feedback:''}
  const [form,setForm]=useState(()=>{try{return {...blank,...item,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return {...blank,...item}}});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const set=(k,v)=>setForm({...form,[k]:v});useEffect(()=>localStorage.setItem(key,JSON.stringify(form)),[form,key])
  const save=async e=>{e.preventDefault();setBusy(true);const payload={...form,owner_id:ownerId,quote_amount:form.quote_amount?Number(form.quote_amount):null,actual_cost:form.actual_cost?Number(form.actual_cost):null,last_followed_up:form.last_followed_up||null,updated_at:new Date().toISOString()};delete payload.properties;const {error:err}=item.id?await supabase.from('maintenance_items').update(payload).eq('id',item.id):await supabase.from('maintenance_items').insert(payload);if(err){setError(err.message);setBusy(false);return}localStorage.removeItem(key);onSaved()}
  const statuses=['Logged','Awaiting inspection','Awaiting quote','Awaiting landlord approval','Repairs scheduled','Awaiting completion confirmation','Completed']
  return <div className="editor-backdrop" onClick={onClose}><form className="lease-editor" onSubmit={save} onClick={e=>e.stopPropagation()}><EditorHead eyebrow="MAINTENANCE FILE" title={item.id?'Edit issue':'Log an issue'} onClose={onClose}/><section className="editor-section"><div className="form-grid"><label>Property<select required value={form.property_id} onChange={e=>set('property_id',e.target.value)}><option value="">Select property</option>{properties.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Reported by<select value={form.reported_by} onChange={e=>set('reported_by',e.target.value)}><option>Landlord</option><option>Tenant</option><option>Contractor</option></select></label><label className="full-field">Issue<input required value={form.issue} onChange={e=>set('issue',e.target.value)} placeholder="Describe the maintenance problem"/></label><label>Status<select value={form.status} onChange={e=>set('status',e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Payment responsibility<select value={form.responsibility} onChange={e=>set('responsibility',e.target.value)}><option>To assess</option><option>Landlord</option><option>Tenant</option><option>Insurance</option><option>Body corporate</option></select></label><label>Contractor<input value={form.contractor||''} onChange={e=>set('contractor',e.target.value)}/></label><label>Last followed up<input type="date" value={form.last_followed_up||''} onChange={e=>set('last_followed_up',e.target.value)}/></label><label>Quote amount (R)<input type="number" min="0" step="0.01" value={form.quote_amount||''} onChange={e=>set('quote_amount',e.target.value)}/></label><label>Final cost (R)<input type="number" min="0" step="0.01" value={form.actual_cost||''} onChange={e=>set('actual_cost',e.target.value)}/></label><label className="urgent-check"><input type="checkbox" checked={form.urgent} onChange={e=>set('urgent',e.target.checked)}/>Urgent issue</label><label className="full-field">Feedback and timeline<textarea rows="5" value={form.feedback||''} onChange={e=>set('feedback',e.target.value)} placeholder="Record calls, quotes, approvals and progress…"/></label></div></section>{error&&<div className="auth-message">{error}</div>}<EditorActions busy={busy} onClose={onClose}/></form></div>
}

export function LearnModule(){const lessons=[['Before advertising','Prepare the property, decide charges and advertise fairly.'],['Screening tenants','Use consistent affordability and reference checks.'],['CPA or non-CPA','Understand why applicability depends on the parties and circumstances.'],['Deposits and interest','Keep the deposit records and required reconciliation evidence.'],['Inspections','Protect both parties with signed, photographic condition reports.'],['Maintenance responsibility','Use the lease, cause and circumstances before allocating cost.'],['Notices and breaches','Use correct notice, delivery proof and remedy periods.'],['Ending a tenancy','Follow lawful cancellation, inspection and deposit steps.']];return <section><div className="page-intro"><div><span className="eyebrow">LANDLORD GUIDANCE</span><h2>Learn as you manage</h2><p>Plain-language guidance appears at the stage where it is useful.</p></div></div><div className="learn-grid">{lessons.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><BookOpen/><h3>{title}</h3><p>{text}</p><small>Educational guidance · Attorney review required for high-risk matters</small></article>)}</div><div className="disclaimer"><AlertTriangle/><div><b>Not personalised legal advice</b><p>Serious breaches, evictions, unusual CPA questions and disputed deductions should be reviewed by a qualified South African attorney.</p></div></div></section>}

function EditorHead({eyebrow,title,onClose}){return <div className="editor-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>Draft saved automatically</p></div><button type="button" onClick={onClose}><X/></button></div>}
function EditorActions({busy,onClose}){return <div className="editor-actions"><button type="button" className="secondary" onClick={onClose}>Close</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save record'}</button></div>}
function ModuleLoading(){return <div className="module-loading"><span/><p>Loading records…</p></div>}
function ModuleEmpty({icon:Icon,title,text}){return <div className="empty-card"><Icon/><h3>{title}</h3><p>{text}</p></div>}
function formatDate(date){return new Intl.DateTimeFormat('en-ZA',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${date}T12:00:00`))}
