import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CalendarDays, CheckCircle2, ClipboardCheck, FileDown, Info, ShieldCheck } from 'lucide-react'

const addDays=(date,days)=>{if(!date)return null;const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+days);return d}
const subDays=(date,days)=>addDays(date,-days)
const fmt=d=>d&&!isNaN(d)?new Intl.DateTimeFormat('en-ZA',{day:'numeric',month:'short',year:'numeric'}).format(d):'Add the lease end date'

const REVIEW_ITEMS=['Rent payment history and any outstanding amounts','Maintenance history and unresolved repairs','Tenant communication and conduct records','Market rental and affordability of proposed increase','Deposit amount and whether a lawful top-up should be agreed','Utilities, services, occupants, pets and property rules','Insurance, compliance documents and body corporate rules','Whether either party wants different terms']
const INSPECTION_ITEMS=['Arrange reasonable access with the tenant in advance','Use the ingoing and interim reports as the baseline','Check roof/water ingress signs, ceilings, walls and floors','Test visible plumbing, sanitaryware, windows, doors and locks','Check appliances/fixtures supplied with the property','Inspect exterior, garden, pool, garage and boundary items where applicable','Record meter readings and photograph maintenance concerns','Separate maintenance from possible tenant-caused damage; do not make deductions now','Agree a written repair list, responsibility still to be confirmed, and target dates']

export function RenewalsModule({properties,notify}){
  const [propertyId,setPropertyId]=useState(properties[0]?.id||'');const property=properties.find(p=>p.id===propertyId);const lease=property?.activeLease||{}
  const key=`myrental_renewal_${propertyId}`
  const initial=()=>{try{return {...{decision:'undecided',leaseEnd:lease.end_date||'',newStart:lease.end_date||'',newEnd:'',newRent:lease.monthly_rent||'',increase:'',noticeDate:'',inspectionDate:'',notes:'',checks:{},inspectionChecks:{}},...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return {decision:'undecided',leaseEnd:lease.end_date||'',checks:{},inspectionChecks:{}}}}
  const [form,setForm]=useState(initial)
  useEffect(()=>setForm(initial()),[propertyId])
  useEffect(()=>{if(propertyId)localStorage.setItem(key,JSON.stringify(form))},[form,key,propertyId])
  const set=(name,value)=>setForm(v=>({...v,[name]:value}))
  const toggle=(group,item)=>setForm(v=>({...v,[group]:{...v[group],[item]:!v[group]?.[item]}}))
  const timeline=useMemo(()=>({start:subDays(form.leaseEnd,100),windowStart:subDays(form.leaseEnd,80),windowEnd:subDays(form.leaseEnd,40),lastMonth:subDays(form.leaseEnd,30),end:addDays(form.leaseEnd,0)}),[form.leaseEnd])
  if(!properties.length)return <section><div className="page-intro"><div><span className="eyebrow">RENEWALS</span><h2>Add a property first</h2><p>The renewal guide uses the property and current lease dates.</p></div></div></section>
  return <section className="renewals-page"><div className="page-intro"><div><span className="eyebrow">GUIDED LEASE REVIEW</span><h2>Renew or end a lease</h2><p>Start early, inspect the property, confirm the legal position and record the decision in writing.</p></div></div>
    <div className="renewal-controls"><label>Property<select value={propertyId} onChange={e=>setPropertyId(e.target.value)}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Current lease ends<input type="date" value={form.leaseEnd||''} onChange={e=>set('leaseEnd',e.target.value)}/></label></div>
    <article className="renewal-rule"><ShieldCheck/><div><b>Do not rely on one universal notice period</b><p>Read the signed lease first and establish whether the CPA applies. If CPA section 14 applies, the supplier’s expiry notice is generally required 40–80 business days before expiry. This is not the same as simply counting calendar days. Applicability and any non-renewal or cancellation notice should be checked professionally.</p></div></article>
    <section className="renewal-timeline"><div><CalendarDays/><span><small>START REVIEW</small><b>{fmt(timeline.start)}</b><p>Recommended planning point, roughly 3 months before expiry.</p></span></div><div><span><small>CPA WINDOW—IF APPLICABLE</small><b>{fmt(timeline.windowStart)} onward</b><p>40–80 business days needs exact calculation; these calendar dates are only an early alert.</p></span></div><div><span><small>DO NOT WAIT UNTIL</small><b>{fmt(timeline.lastMonth)}</b><p>Avoid leaving negotiation or non-renewal until the final month.</p></span></div><div><span><small>LEASE EXPIRY</small><b>{fmt(timeline.end)}</b><p>Ensure the signed outcome and next steps are clear before this date.</p></span></div></section>
    <div className="renewal-grid"><section className="renewal-card"><span className="eyebrow">STEP 1</span><h2>Review before deciding</h2>{REVIEW_ITEMS.map(x=><label className="renew-check" key={x}><input type="checkbox" checked={!!form.checks?.[x]} onChange={()=>toggle('checks',x)}/><span><CheckCircle2/>{x}</span></label>)}</section><section className="renewal-card"><span className="eyebrow">STEP 2</span><h2>Recommended pre-renewal inspection</h2><p className="card-intro">This is a condition and maintenance review, not the statutory outgoing inspection. Arrange access reasonably and respect the tenant’s privacy.</p>{INSPECTION_ITEMS.map(x=><label className="renew-check" key={x}><input type="checkbox" checked={!!form.inspectionChecks?.[x]} onChange={()=>toggle('inspectionChecks',x)}/><span><ClipboardCheck/>{x}</span></label>)}<label className="date-field">Inspection date<input type="date" value={form.inspectionDate||''} onChange={e=>set('inspectionDate',e.target.value)}/></label></section></div>
    <section className="renewal-decision"><span className="eyebrow">STEP 3</span><h2>Record the decision</h2><div className="decision-buttons">{[['renew','Offer / agree renewal'],['not-renew','Do not renew'],['undecided','Still deciding']].map(([id,label])=><button className={form.decision===id?'active':''} onClick={()=>set('decision',id)} key={id}>{label}</button>)}</div>
      {form.decision==='renew'&&<div className="renewal-form"><label>New lease starts<input type="date" value={form.newStart||''} onChange={e=>set('newStart',e.target.value)}/></label><label>New lease ends<input type="date" value={form.newEnd||''} onChange={e=>set('newEnd',e.target.value)}/></label><label>New monthly rental (R)<input type="number" value={form.newRent||''} onChange={e=>set('newRent',e.target.value)}/></label><label>Increase / reason<input value={form.increase||''} onChange={e=>set('increase',e.target.value)} placeholder="Record calculation or agreed change"/></label><label className="wide">Other changed terms<textarea value={form.notes||''} onChange={e=>set('notes',e.target.value)} placeholder="Deposit top-up, utilities, occupants, pets or other agreed changes"/></label><div className="renewal-next wide"><b>Next:</b> Put every change in a signed renewal addendum before the old lease expires. Do not rely on verbal agreement. The Documents section can prepare the draft.</div></div>}
      {form.decision==='not-renew'&&<div className="nonrenewal"><AlertTriangle/><div><b>Before giving non-renewal notice</b><ol><li>Check the renewal, expiry, notice and cancellation clauses.</li><li>Establish whether the CPA applies and calculate business days correctly.</li><li>Do not describe a fixed-term expiry as an eviction or use self-help measures.</li><li>Deliver the written notice using a method permitted by the lease and keep proof.</li><li>Arrange the statutory joint outgoing inspection within the three days before expiry.</li><li>Get attorney advice if occupation may continue, notice is late, or the tenant disputes termination.</li></ol><label>Planned notice date<input type="date" value={form.noticeDate||''} onChange={e=>set('noticeDate',e.target.value)}/></label></div></div>}
    </section>
    <article className="renewal-info"><Info/><p><b>Helpful knowledge—not legal advice.</b> Lease expiry, renewal, cancellation and notice requirements can change according to the parties, agreement, CPA application and facts. MyRental SA does not determine whether a tenancy has legally ended. Consult a qualified South African property attorney where necessary.</p></article>
  </section>
}
