import { useState } from 'react'
import { Building2, Check, ChevronRight, HelpCircle, KeyRound, Mail, Save, ShieldCheck, UserRound } from 'lucide-react'
import { supabase } from './supabase'

export function ProfessionalHelp(){
  const reasons=['You do not have time for follow-ups, inspections and maintenance coordination','You are unsure about screening, lease terms, notices or legal processes','The property is far from where you live','A tenant dispute, serious breach or eviction risk has developed','You prefer professional rental collection and administration']
  return <section><div className="page-intro"><div><span className="eyebrow">CHOOSING HOW TO MANAGE</span><h2>Would professional management suit you better?</h2><p>Self-management is not the right choice for every landlord—and asking for help is often the responsible decision.</p></div></div><div className="management-choice"><article><span><UserRound/></span><h3>Continue self-managing</h3><p>Use MyRental SA for organisation, records, reminders and general guidance while you remain responsible for every decision.</p><ul><li><Check/>You have time to manage the property</li><li><Check/>You are comfortable obtaining legal advice when required</li><li><Check/>You keep reliable records and follow deadlines</li></ul></article><article className="featured-choice"><span><Building2/></span><h3>Appoint a rental agent</h3><p>A professional agent can handle tenant procurement, screening, lease negotiation, rental administration, maintenance and inspections.</p><ul>{reasons.slice(0,3).map(x=><li key={x}><Check/>{x}</li>)}</ul></article></div><div className="agent-recommendation"><div><span className="eyebrow">A RECOMMENDED PROFESSIONAL OPTION</span><h2>Pam Golding Properties Rentals</h2><p>Pam Golding Properties describes itself as Southern Africa’s leading independent real-estate group. Its specialist rental agents offer tenant procurement, screening and credit checks, lease negotiation, collections, maintenance management and inspections.</p><a href="https://www.pamgolding.co.za/about-us" target="_blank" rel="noreferrer">Explore Pam Golding rental services <ChevronRight/></a></div><div className="affiliation"><ShieldCheck/><div><b>You remain free to choose</b><p>MyRental SA does not require landlords to appoint Pam Golding Properties. You may compare services, fees and credentials and appoint any suitably qualified property practitioner.</p></div></div></div><div className="help-warning"><HelpCircle/><div><b>When an attorney—not only an agent—is needed</b><p>Use a qualified South African attorney for eviction, serious breach, contested cancellation, disputed deductions or unusual legal questions. An agent cannot replace legal representation.</p></div></div></section>
}

export function SettingsModule({user,profile,onProfileUpdated}){
  const [form,setForm]=useState({full_name:profile?.full_name||'',phone:profile?.phone||''});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('')
  const save=async()=>{setBusy(true);setMessage('');const {data,error}=await supabase.from('profiles').update({...form,updated_at:new Date().toISOString()}).eq('id',user.id).select().single();setBusy(false);if(error)setMessage(error.message);else{onProfileUpdated(data);setMessage('Account details saved')}}
  const reset=async()=>{setBusy(true);setMessage('');const {error}=await supabase.auth.resetPasswordForEmail(user.email,{redirectTo:window.location.origin});setBusy(false);setMessage(error?error.message:'Password-reset email sent')}
  return <section><div className="page-intro"><div><span className="eyebrow">ACCOUNT & SECURITY</span><h2>Settings</h2><p>Manage your landlord profile and account access.</p></div></div><div className="settings-grid"><article><div className="settings-title"><UserRound/><div><h3>Landlord profile</h3><p>Used to personalise your account.</p></div></div><label>Full name<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Mobile number<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email address<input disabled value={user.email}/></label><button className="primary" onClick={save} disabled={busy}><Save/>Save details</button></article><article><div className="settings-title"><KeyRound/><div><h3>Password and access</h3><p>Your session stays active unless you sign out.</p></div></div><div className="account-line"><Mail/><div><small>SIGNED IN AS</small><b>{user.email}</b></div></div><button className="secondary settings-action" onClick={reset} disabled={busy}>Send password-reset email</button><p className="settings-note">Never share verification codes, passwords or email access with support staff.</p></article></div>{message&&<div className="settings-message">{message}</div>}</section>
}
